CREATE DATABASE IF NOT EXISTS lr_php CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS users (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(50) NOT NULL UNIQUE,
	email VARCHAR(255) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME NULL
);

CREATE TABLE IF NOT EXISTS profiles (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	user_id INT UNSIGNED NOT NULL,
	firstname VARCHAR(50) NULL,
	lastname VARCHAR(50) NULL,
	bio VARCHAR(255) NULL,
	gender BOOLEAN NULL,
	birthdate DATE NULL,
	phone_number VARCHAR(15) NULL,
	address VARCHAR(255) NULL,
	city VARCHAR(100) NULL,
	country VARCHAR(50) NULL,
	code_postal INT NULL,
	updated_at DATETIME NULL
);

ALTER TABLE profiles ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;